### ISSUE TITLE
Not an issue but no discussion section - Question on PIS from Fysetc. 

### ISSUE THREAD

**Issue by tinymachines3d** [rogerlz/rampon_anchor#3]
**Does this work with the PIS from Fysetc?** Currently, it uses the gpio pins below. 

[mcu PIS]
serial: /dev/serial/by-id/usb-Klipper_rp2040_E66160F42361C137-if00

[adxl345]
cs_pin: PIS:gpio13
#spi_bus: spi1a
spi_software_sclk_pin: PIS:gpio10
spi_software_mosi_pin: PIS:gpio11
spi_software_miso_pin: PIS:gpio12

**Comment by rogerlz** [comment]
Hi @tinymachines3d, unfortunately, no. It has the pins hardcoded for KUSBA (https://github.com/rogerlz/rampon_anchor/blob/main/src/main.rs#L95-L98)

If you can send me a link for PIS schematics and give me a couple of days I can create a version for it. 

edit: found it here: https://github.com/FYSETC/FYSETC-PortableInputShaper/blob/main/PIS.pdf

**Comment by tinymachines3d** [comment]
That's it! The link below has all the other info provided. 

https://github.com/FYSETC/FYSETC-PortableInputShaper

It doesn't suffer from the same issues as other 2040 chips but it does require a power cycle after reboot to connect back up to klipper. I've created a workaround that modifies the printer.cfg with sed -i command turning the mcu off and off by commenting out the file or uncommenting it with macros that are inserted into the input shaper macro. 

![image](https://user-images.githubusercontent.com/28379694/229958050-0115edc9-2c8b-44ed-8718-2d07d69c2a01.png)

**Comment by rogerlz** [comment]
@tinymachines3d can you ping me on discord? I can send you a version to test. 
rogerlz#2677

**Comment by rogerlz** [comment]
this is fixed #4
