### ISSUE TITLE
Request to add support for Mellow nozzle ADXL

### ISSUE THREAD

**Issue by staticanime** [rogerlz/rampon_anchor#5]
Link to product: https://www.aliexpress.com/item/1005006003342822.html
Link to schematics: https://github.com/Mellow-3D/USB-Accelerometer/blob/main/Hardware/USB%20Accelerometer%20Schematic.pdf

[adxl345]
cs_pin: adxl:gpio9
spi_software_sclk_pin: adxl:gpio10
spi_software_mosi_pin: adxl:gpio11
spi_software_miso_pin: adxl:gpio12

**Comment by rogerlz** [comment]
Hey! Sorry for the time it took me to work on this. I have released a new version to support this board. Let me know if it works :)
